<?php

require('fpdf/fpdf.php');
$pdf = new FPDF();
$pdf->AddPage();
//$pdf->Image('../images/Border4.png', 5, 5, 200, 290);
$pdf->Image('assets/img/logo.jpg', 15, 10, 180, 20);
$pdf->Cell(100, 3, "");
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(180, 3, "PURCHASE ORDER", 0, 0, 'R');
$pdf->Ln();
$pdf->Cell(100, 5, "TO,");
$pdf->Ln();
$pdf->Cell(100, 5, "UDAYA PAYING BLOCKS");
$pdf->SetFont('Arial', 'B', 7);
$pdf->Ln();
$pdf->Cell(150, 5, "#42,Ramohalli, Mukthinaga Temple Road,");
$pdf->Ln();
$pdf->Cell(150, 5, "(Dodda Aladamara Road),");
$pdf->Ln();
$pdf->Cell(150, 5, "Kengeri Hobli, Bangalore-560074");
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 8);
$pdf->Ln();
$pdf->Cell(150, 5, "Billing Address:");
$pdf->Ln();
$pdf->Cell(150, 5, "Integra Office Solution");
$pdf->SetFont('Arial', 'B', 7);
$pdf->Ln();
$pdf->Cell(150, 5, "No 80, 12th Main Road");
$pdf->Ln();
$pdf->Cell(150, 5, "Hongasandra, Begur Road");
$pdf->Ln();
$pdf->Cell(150, 5, "Bommanahalli, Bangalore-560068");
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
//$pdf->SetFont('Arial',9);
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(150, 3, "Subject: Quotation Designer Pavers & Kerb Stone");
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial', 'BU', 9);
$pdf->Cell(150, 3, "Kindly Attend: Mr. Raju Sagar Gowda");
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial');
$pdf->SetFontSize(8);
$pdf->Cell(150, 3, "Dear Sir/Madam");
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(150, 3, " As Per discussion, we are pleased to place an order as mentioned below.");
$pdf->Ln();
$pdf->Ln();
$pdf->SetFillColor(164, 161, 161);
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(20, 5, "SNo", 1, 0, 'C', TRUE);
$pdf->Cell(160, 5, "Description", 1, 0, 'C', TRUE);
$pdf->Ln();
$pdf->SetFillColor(0, 0, 0);
$pdf->SetFont('Arial');
$pdf->SetFontSize(8);
$pdf->Cell(20, 5, "1", 1, 0, 'C');
$pdf->Cell(160, 5, "Desiner pavers Rubber Mould Zigzag 80mm", 1, 0);
$pdf->Ln();
$pdf->Cell(20, 5, "2", 1, 0, 'C');
$pdf->Cell(160, 5, "Kerb Stone 500x330x150mm(Hydraulic press)", 1, 0);
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(160, 5, "Amount in words: One Lakh Eighty Six Thousand Only");
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 8);
$pdf->Cell(160, 5, "Terms and Conditions:");
$pdf->SetFont('Arial');
$pdf->SetFontSize(8);
$pdf->Ln();
$pdf->Cell(160, 5, "Payment : 50% Advance and 50% after Completion");
$pdf->Ln();
$pdf->Cell(160, 5, "Delivery : Immediate");
$pdf->Ln();
$pdf->Cell(160, 5, "Taxes as applicable");
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->SetFont('Arial', 'B', 7);
$pdf->Cell(160, 5, 'For Integra Office Solution');
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Ln();
$pdf->Cell(160, 5, 'Authorized Signatory');
$pdf->SetX(10);
$pdf->SetY(-40);
$pdf->SetFont('Arial', 'B', 8);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFillColor(255, 255, 255);
$pdf->Cell(160, 5, "___________________________________________________________________________________________________________________________");
$pdf->Ln();
$pdf->Cell(180, 5, " No,8 12th main Road, Hongasandra, Begur Road, Bommanahalli,Bangalore-560068", 0, '', 'C');
$pdf->SetFont('Arial', 'B', 10);
$pdf->Ln();
$pdf->Cell(180, 5, " TIN NO :29250827", 0, '', 'R');
$pdf->Output("Purchase Order.pdf", 'I');
?>