<?php
                define("MODULE_1","config.php");
                require_once (MODULE_1);
                define("MODULE_2","database.php");
                define("APP_MODULE","appcontroller.php");
                require_once(MODULE_1);
                require_once(CONFIG_ROOT.MODULE_1);
                require_once(CONFIG_ROOT.MODULE_2);
                require_once(LIB_ROOT.PDF);
                $parameters=array();
                $parameter[]=$_SESSION['pdfbillgeneration'];
//                print_r($parameter);
                $pdf=new FPDF();
                $pdf->AddPage();
                $pdf->SetFont('Arial','B',12);
                $pdf->SetTextColor(0,0,0);
                $pdf->Cell(90,5,"Prepaid Auto Rickshaw Service",0, 0,'C');
                $pdf->Image('assets/img/autorickshaw.jpg', 15, 6, 15, 15);
                $pdf->Ln();
                $pdf->Ln();$pdf->Ln();
                $pdf->SetFont('Arial','B',8);
                $pdf->Cell(80,4,"Auto Booking Details: ",0, 0,'L');
                $pdf->Ln();
                $pdf->Cell(80,4,"Dear ".$_SESSION['pdfbillgeneration']['passengername'],0, 0,'L');
                $pdf->SetFont('Arial','',8);
                $pdf->Ln();
                $pdf->Cell(25,4,"Booking Ref. no",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(25,4,"BKID-".$_SESSION['pdfbillgeneration']['bookid'],0, 0,'L');
                $pdf->Ln();
                $pdf->Cell(25,4,"Pick-up Time",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $d=strtotime("10:30pm April 15 2014");
                $pdf->Cell(25,4,date("l jS \of F Y h:i:s A"),0, 0,'L');
                $pdf->Ln();
                $pdf->Cell(25,4,"From",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(80,4,  $_SESSION['pdfbillgeneration']['source'],0, 0,'L');
                $pdf->Ln();
                $pdf->Cell(25,4,"TO",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(80,4,  $_SESSION['pdfbillgeneration']['destination'],0, 0,'L');
                $pdf->Ln();
                $pdf->SetFont('Arial','B',8);
                $pdf->Ln();
                $pdf->Cell(80,4,"Auto/Chauffeur Details: ",0, 0,'L');
                $pdf->SetFont('Arial','',8);
                $pdf->Ln();
                $pdf->Cell(25,4,"Auto Number",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(40,4,  $_SESSION['pdfbillgeneration']['regdno'],0, 0,'L');
                $pdf->Ln();
                $pdf->Cell(25,4,"Chauffeur Name",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(40,4, $_SESSION['pdfbillgeneration']['drivername'],0, 0,'L');
                $pdf->Ln();
                $pdf->Cell(25,4,"Chauffeur Mobile",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(40,4,$_SESSION['pdfbillgeneration']['drivermobile'],0, 0,'L');
                $pdf->Ln();$pdf->Ln();
                $pdf->SetFont('Arial','B',8);
                $pdf->Cell(80,4,"Billing Details: ",0, 0,'L');
                $pdf->Ln();
                $pdf->SetFont('Arial','',8);
                $pdf->Cell(25,4,"Base Fare",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(20,4, "Rs.50/-",0, 0,'R');
                $pdf->Ln();
                $pdf->Cell(25,4,"Extra KM Fare",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(20,4,"Rs.10/-",0, 0,'R');
                $pdf->Ln();
                $pdf->Cell(25,4,"Distance Travelled",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(20,4,$_SESSION['pdfbillgeneration']['distance'].'.00',0, 0,'R');
                $pdf->SetFont('Arial','B',8);
                $pdf->Ln();
                $pdf->Cell(25,4,"Amount",0, 0,'R');
                $pdf->Cell(2,4,"",0, 0,'L');
                $pdf->Cell(20,4,$_SESSION['pdfbillgeneration']['amount'].'.00',0, 0,'R');
                $pdf->Ln();
                $pdf->Ln();
                $pdf->Cell(80,4,"THANK YOU FOR TRUSTING US",0, 1,'C');
                $pdf->Ln();$pdf->Ln();
                $pdf->Cell(50,4,"",0, 0);
                $pdf->Cell(30,4,"Authorised Signature",0, 0,'L');
                $pdf->Output('AutoBill.pdf','I');
