<?php

class adminReport {

    protected $parameters = array();

    function __construct($para = false) {
        $this->parameters = $para;
    }

    public function projectsReports() {
        $query = 'SELECT
                        eng.*,
                        pact.activity_name,
                        pact.description,
                        proj.project_name,
                        up.emp_id,
                        up.user_name
                      FROM engage eng
                        LEFT JOIN projects_activity pact
                          ON pact.id = eng.project_activity_id
                        LEFT JOIN projects proj
                          ON proj.id = pact.project_id
                        LEFT JOIN user_profile up
                          ON up.id = eng.created_by
                      WHERE eng.status_id = 16
                          AND proj.id = "' . $this->parameters['selectproj'] . '"';
        $result = executeQuery($query);
        if (mysql_num_rows($result)) {
            $fetchdata = array();
            while ($row = mysql_fetch_assoc($result)) {
                $fetchdata[] = $row;
            }

            $objPHPExcel = new PHPExcel();
            $headers = array('font' => array('bold' => true, 'color' => array('rgb' => '000000'), 'size' => 10, 'name' => 'Arial'), 'alignment' => array('horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER, 'vertical' => PHPExcel_Style_Alignment::VERTICAL_CENTER),);
            $sheet = $objPHPExcel->getActiveSheet();
            $rows = 1;
            $objPHPExcel->getProperties()->setCreator($_SESSION['USER_LOGIN_DATA']['USER_NAME'])
                    ->setLastModifiedBy($_SESSION['USER_LOGIN_DATA']['USER_NAME'])
                    ->setTitle("Project Report")
                    ->setSubject("Project Report")
                    ->setDescription("Report generated by Powered By MadMec.")
                    ->setKeywords("MadMec")
                    ->setCategory("Reports");
            /* Set active sheet */
            $objPHPExcel->setActiveSheetIndex(0);
            /* Set page size */
            $objPHPExcel->getActiveSheet()
                    ->getPageSetup()
                    ->setOrientation(PHPExcel_Worksheet_PageSetup::ORIENTATION_LANDSCAPE);
            $objPHPExcel->getActiveSheet()
                    ->getPageSetup()
                    ->setPaperSize(PHPExcel_Worksheet_PageSetup::PAPERSIZE_A4);
            /* Add a header */
            $objPHPExcel->getActiveSheet()
                    ->getHeaderFooter()
                    ->setOddHeader('&C&H '.$fetchdata[0]['project_name'].' Project report ');
            /* Add a footer */
            $objPHPExcel->getActiveSheet()
                    ->getHeaderFooter()
                    ->setOddFooter('&L&B' . $objPHPExcel->getProperties()->getTitle() . '&RPage &P of &N');
            /*
              Set printing area
              $objPHPExcel->getActiveSheet()->getPageSetup()->setPrintArea('A1:H1');
             */
            /*
              Set printing break
              $objPHPExcel->getActiveSheet()->setBreak( 'A47' , PHPExcel_Worksheet::BREAK_ROW );
             */
            /* Add titles  of the columns */
            $objPHPExcel->getActiveSheet()
                    ->setCellValueByColumnAndRow(0, 1, 'No')
                    ->setCellValueByColumnAndRow(1, 1, 'Employee_ID')
                    ->setCellValueByColumnAndRow(2, 1, 'Employee Name')
                    ->setCellValueByColumnAndRow(3, 1, 'IN Time')
                    ->setCellValueByColumnAndRow(4, 1, 'OUT Time')
                    ->setCellValueByColumnAndRow(5, 1, 'Activity')
                    ->setCellValueByColumnAndRow(6, 1, 'Description');
            /* Setting a column’s width */
            /* header bold */
            $sheet->getStyle($rows)->applyFromArray($headers);
            foreach (range('A', 'E') as $columnID) {
                $objPHPExcel->getActiveSheet()->getColumnDimension($columnID)
                        ->setAutoSize(true);
            }
            /* 4.6.12.	Center a page horizontally/vertically */
            $objPHPExcel->getActiveSheet()->getPageSetup()->setHorizontalCentered(true);
            /* 4.6.33.	Group/outline a row */
            $objPHPExcel->getActiveSheet()->getRowDimension('1')->setOutlineLevel(2);
            for ($i = 1; $i <= sizeof($fetchdata); $i++) {
                $objPHPExcel->getActiveSheet()
                        ->setCellValueByColumnAndRow(0, ($i + 1), $i)
                        ->setCellValueByColumnAndRow(1, ($i + 1), $fetchdata[($i-1)]['emp_id'])
                        ->setCellValueByColumnAndRow(2, ($i + 1), $fetchdata[($i-1)]['user_name'])
                        ->setCellValueByColumnAndRow(3, ($i + 1), $fetchdata[($i-1)]['in_time'])
                        ->setCellValueByColumnAndRow(4, ($i + 1), $fetchdata[($i-1)]['out_time'])
                        ->setCellValueByColumnAndRow(5, ($i + 1), $fetchdata[($i-1)]['activity_name'])
                        ->setCellValueByColumnAndRow(6, ($i + 1), $fetchdata[($i-1)]['description']);
            }
            $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
            $callStartTime = microtime(true);
            $filename = $fetchdata[0]['project_name']. '_' . $objPHPExcel->getProperties()->getTitle() . '_' . date('j-M-Y') . '_' . '_' . $callStartTime . '.xlsx';
            $objWriter->save(DOC_ROOT . DOWNLOADS . $filename);
            unset($objWriter);
            unset($objPHPExcel);
            return '<center><h3>Click on below link to download</h3><h4><a target="_blank" href="' . URL . DOWNLOADS . $filename . '">' . $filename . '</a></h4></center>';
        }
    }

}
