<?php
$privacy = isset($this->idHolders["nookleads"]["index"]["privacy"]) ? (array) $this->idHolders["nookleads"]["index"]["privacy"] : false;
?>
<div class="container">
    <div class="col-lg-12">&nbsp;</div>  <div class="col-lg-12">&nbsp;</div>  <div class="col-lg-12">&nbsp;</div>
    <div class="about-main">
        <div class="row">
            <h2>Privacy</h2>
            <div class="col-lg-12">&nbsp;</div>
            <div class="nookleads">
                 <strong>Accepting the Terms of Service</strong>
                <p class="text-justify">
                    <b> •	Introduction  </b></br>
                    nookleads, takes the private nature of your personal information very seriously.</br>
                    This privacy policy, which we adapted from a policy originally provided by Automattic (WordPress.com)and 9GAG, describes how we treat the information we collect when you visit and use our websites. Please read this notice very carefully.</br>
                    <b> •	Website Visitors</b></br>
                    Approval most website operators, nookleads collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. nookleads’s purpose in collecting non-personally identifying information is to better understand how nookleads’s visitors use its website. From time to time, nookleads may release non-personally-identifying information in the aggregate, e.g. by publishing a report on trends in the usage of its website.</br>
                    nookleads also collects potentially personally-identifying information approval Internet Protocol (IP) addresses. nookleads does not use such information to identify its visitors, and does not disclose such information, other than under the same circumstances that it uses and discloses personally-identifying information, as described below.</br>
                    <b> •	Gathering of Personally-Identifying Information</b></br>
                    Certain visitors to nookleads’s websites choose to interact with nookleads in ways that require nookleads to gather personally-identifying information. The amount and type of information that nookleads gathers depends on the nature of the interaction. For example, we ask visitors who sign up for nookleads.com to provide a username and email address. In each case, nookleads collects such information only insofar as is necessary or appropriate to fulfil the purpose of the visitor’s interaction with nookleads. nookleads does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</br>
                    <b> •	Aggregated Statistics</b></br>
                    nookleads may collect statistics about the behaviour of visitors to its websites. For instance, nookleads may monitor the most popular collections on nookleads.com. nookleads may display this information publicly or provide it to others. However, nookleads does not disclose personally-identifying information other than as described below.</br>
                    <b> •	Protection of Certain Personally-Identifying Information</b></br>
                    nookleads discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on nookleads’s behalf or to provide services available at nookleads’s websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using nookleads’s websites, you consent to the transfer of such information to them. In addition, in some cases we may choose to buy or sell assets. In these types of transactions, user information is typically one of the business assets that is transferred. Moreover, if nookleads or substantially all of its assets were acquired, or in the unapprovally event that nookleads goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of nookleads may continue to use your personal and non-personal information only as set forth in this policy. Otherwise, nookleads will not rent or sell potentially personally-identifying and personally-identifying information to anyone.</br>
                <div class="col-lg-12">&nbsp;</div>
                Other than to its employees, contractors and affiliated organizations, as described above, nookleads discloses potentially personally-identifying and personally-identifying information only when required to do so by law, or when nookleads believes in good faith that disclosure is reasonably necessary to protect the property or rights of nookleads, third parties or the public at large. If you are a registered user of a nookleads website and have supplied your email address, nookleads may occasionally send you an email to tell you about new features, solicit your feedback, or just keep you up to date with what’s going on with nookleads and its products. If you send us a request (for example via a support email or via one of our feedback mechanisms), we reserve the right to publish it in order to help us clarify or respond to your request or to help us support other users. nookleads takes all measures reasonably necessary to protect against the unauthorized access, use, alteration or destruction of potentially personally-identifying and personally-identifying information.</br>
                <div class="col-lg-12">&nbsp;</div>
                <b> We may use your date of birth to wish you on your birthday and also organise a surprise party in your country.</b> </br>
                <div class="col-lg-12">&nbsp;</div>
                You should also be aware that if you submit information to “chat rooms,” “forums” or “message boards” such information becomes public information, meaning that you lose any privacy rights you might have with regards to that information. Such disclosures may also increase your chances of receiving unwanted communications.</br>
                <b> •	Cookies</b></br>
                A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. nookleads uses cookies to help nookleads identify and track visitors, their usage of nookleads websites, and their website access preferences. nookleads visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using nookleads’s websites, with the drawback that certain features of nookleads’s websites may not function properly without the aid of cookies.</br>
                <b> •	Ads</b>
                Ads appearing on any nookleads websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This privacy policy covers the use of cookies by nookleads and does not cover the use of cookies by any advertisers.</br>
                <b> •	Links to Third Party Sites</b></br>
                This privacy policy only applies to information collected by nookleads. This privacy policy does not apply to the practices of companies that nookleads does not own or control, or employees that nookleads does not manage. A nookleads website may contain links to third party websites. Any information you provide to, or that is collected by, third-party sites may be subject to the privacy policies of those sites, if any. We encourage you to read such privacy policies of any third-party sites you visit. It is the sole responsibility of such third parties to adhere to any applicable restrictions on the disclosure of your personally-identifying information, and nookleads and its affiliates shall not be liable for wrongful use or disclosure of your personally-identifying information by any third party.</br>
                <b> •	Security</b></br>
                All non-personally-identifying information, potentially personally-identifying and personally identifying-information described above is stored on restricted database servers.</br>
                <b> •	Choice/Opt-out</b></br>
                If we ever send you information by email concerning new products, services or information that you did not expressly request, we will provide you with an email address by which you may request no further notices.</br>
                <b> •	Address Book Data</b></br>
                Any external address book data (email contacts, etc.) that a user voluntarily gives nookleads access to will only be used for the described feature (looking up friends, etc.), and will not be stored or repurposed.</br>
                <b> •	Privacy Policy Changes</b></br>
                Although most changes are approvally to be minor, nookleads may change its privacy policy from time to time, and in nookleads’s sole discretion. nookleads encourages visitors to frequently check this page for any changes to its privacy policy. Your continued use of this site after any change in this privacy policy will constitute your acceptance of such change.</br>
                <b> •	Contact Us</b></br>
                If you have any questions about this privacy policy or our sites in general, please contact us.</br>
                </p>
            </div>
        </div>
    </div>
