<?php
$terms = isset($this->idHolders["pic3pic"]["index"]["terms"]) ? (array) $this->idHolders["pic3pic"]["index"]["terms"] : false;
?>
 
        
        <div class="container">
            <div class="col-lg-12">&nbsp;</div>  <div class="col-lg-12">&nbsp;</div>  <div class="col-lg-12">&nbsp;</div>
            <div class="about-main">
                <div class="row">
                    <h2>Terms of services</h2>
                    <h4><strong>Accepting the Terms of Service</strong></h4>
                    <p class="text-justify">
                        The purpose of this website, pic3pic.com (the “Site”), owned and operated by respective Copyright holder is to provide web publishing services and other services. This is a beta version of the site pic3pic. Please read these terms of service (“Agreement”) carefully before using the Site or any services provided on the Site (collectively, “Services”). By using or accessing the Services, you agree to become bound by all the terms and conditions of this Agreement. If you do not agree to all the terms and conditions of this Agreement, do not use the Services. The Services are accessed by You (“Subscriber” or “You”) under the following terms and conditions:
                    </p>
                    <h4><b>1. Access to the Services</b></h4>
                    <p class="text-justify">
                        Subject to the terms and conditions of this Agreement, pic3pic.commay offer to provide the Services, as described more fully on the Site, and which are selected by Subscriber, solely for Subscriber’s own use, and not for the use or benefit of any third party. Services shall include, but not be limited to, any services pic3pic.com performs for Subscriber, as well as the offering of any Content (as defined below) on the Site. pic3pic.com may change, suspend or discontinue the Services at any time, including the availability of any feature, database, or Content. pic3pic.com may also impose limits on certain features and services or restrict Subscriber’s access to parts or all of the Services without notice or liability. pic3pic.com reserves the right, at its discretion, to modify these Terms of Service at any time by posting revised Terms of Service on the Site and by providing notice via e-mail, where possible, or on the Site. Subscriber shall be responsible for reviewing and becoming familiar with any such modifications. Use of the Services by Subscriber following such modification constitutes Subscriber's acceptance of the terms and conditions of this Agreement as modified.
                        Subscriber certifies to pic3pic.com that if Subscriber is an individual (i.e., not a corporate entity), Subscriber is at least 13 years of age. No one under the age of 13 may provide any personal information to or on pic3pic.com (including, for example, a name, address, telephone number or email address). Subscriber also certifies that it is legally permitted to use the Services and access the Site, and takes full responsibility for the selection and use of the Services and access of the Site. This Agreement is void where prohibited by law, and the right to access the Site is revoked in such jurisdictions. pic3pic.com makes no claim that the Site may be lawfully viewed or that Content may be downloaded outside of India. Access to the Content may not be legal by certain persons or in certain countries. If you access the Site from outside India, You do so at Your own risk and You are responsible for compliance with the laws of Your jurisdiction.
                        pic3pic.com will use reasonable efforts to ensure that the Site and Services are available twenty-four hours a day, seven days a week. However, there will be occasions when the Site and/or Services will be interrupted for maintenance, upgrades and repairs or due to failure of telecommunications links and equipment. Every reasonable step will be taken by pic3pic.com to minimize such disruption where it is within pic3pic.com’s reasonable control.
                        You agree that neither pic3pic.com nor the Site will be liable in any event to you or any other party for any suspension, modification, discontinuance or lack of availability of the Site, the service, your Subscriber Content or other Content.
                        pic3pic.com retains the right to create limits on use and storage in its sole discretion at any time with or without notice.
                        Subscriber shall be responsible for obtaining and maintaining any equipment or ancillary services needed to connect to, access the Site or otherwise use the Services, including, without limitation, modems, hardware, software, and long distance or local telephone service. Subscriber shall be responsible for ensuring that such equipment or ancillary services are compatible with the Services.
                    </p>	
                    <h4><b>2. Site Content</b></h4>
                    <p class="text-justify">
                        The Site and its contents are intended solely for the use of pic3pic.com Subscribers and may only be used in accordance with the terms of this Agreement. All materials displayed or performed on the Site, including, but not limited to text, graphics, logos, tools, photographs, images, illustrations, software or source code, audio and video, animations and Themes (as defined below), including without limitation the pic3pic.com Template Code (as defined below) (collectively, “Content”) (other than Content posted by Subscriber (“Subscriber Content”)) are the property of pic3pic.com and/or third parties and are protected by Indian law The pic3pic.com API shall be used solely pursuant to the terms of the API Terms of Service. All trademarks, service marks, and trade names are proprietary to pic3pic.com and/or third parties. Subscriber shall abide by all copyright notices, information, and restrictions contained in any Content accessed through the Services.
                        The Site is protected by copyright as a collective work and/or compilation, pursuant to Indian copyright laws, international conventions, and other copyright laws. Other than as expressly set forth in this Agreement, Subscriber may not copy, modify, publish, transmit, upload, participate in the transfer or sale of, reproduce (except as provided in this Section), create derivative works based on, distribute, perform, display, or in any way exploit, any of the Content, software, materials, or Services in whole or in part.
                        Subscriber may download or copy the Content, and other items displayed on the Site for download, for personal use only, provided that Subscriber maintains all copyright and other notices contained in such Content. Downloading, copying, or storing any Content for other than personal, non-commercial use is expressly prohibited without prior written permission from pic3pic.com, or from the copyright holder identified in such Content's copyright notice. In the event You download software from the Site, the software, including any files, images incorporated in or generated by the software, and the data accompanying the software (collectively, the “Software”) is licensed to You by pic3pic.com or third party licensors for Your personal, non-commercial use, and no title to the Software shall be transferred to You. You may own the Subscriber Content on which the Software is recorded, but pic3pic.com or third party licensors retain full and complete title to the Software and all intellectual property rights therein.
                    </p>
                    <h4><b>3. Subscriber Content</b></h4>
                    <p class="text-justify">
                        Subscriber shall own all Subscriber Content that Subscriber contributes to the Site and site channel but hereby grants and agrees to grant pic3pic.com a non-exclusive, worldwide, royalty-free, transferable right and license (with the right to sublicense), to use, copy, cache, publish, display, distribute, modify, create derivative works and store such Subscriber Content and to allow others to do so (“Content License”) in order to provide the Services
                        pic3pic gives no guarantee that your channel will be selected for unique loyalty program in spite of having large subscribers and many daily unique visitors.No loyalty is given on the content you provide to the site or channel. We pay you only if advertisement is shown in your channel. You have the right to select or reject any advertisement in your channel. On termination of Subscriber’s membership to the Site and use of the Services, pic3pic.com shall make all reasonable efforts to promptly remove from the Site and cease use of the Subscriber Content; however, Subscriber recognizes and agrees that caching of or references to the Subscriber Content may not be immediately removed. Subscriber warrants, represents and agrees Subscriber has the right to grant pic3pic.com and the Site the rights set forth above. Subscriber represents, warrants and agrees that it will not contribute any Subscriber Content that (a) infringes, violates or otherwise interferes with any copyright or trademark of another party, (b) reveals any trade secret, unless Subscriber owns the trade secret or has the owner’s permission to post it, (c) infringes any intellectual property right of another or the privacy or publicity rights of another, (d) is libelous, defamatory, abusive, threatening, harassing, hateful, offensive or otherwise violates any law or right of any third party, (e) contains a virus, trojan horse, worm, time bomb or other computer programming routine or engine that is intended to damage, detrimentally interfere with, surreptitiously intercept or expropriate any system, data or information, or (f) remains posted after Subscriber has been notified that such Subscriber Content violates any of sections (a) to (e) of this sentence. pic3pic.com reserves the right to remove any Subscriber Content from the Site, suspend or terminate Subscriber’s right to use the Services at any time, or pursue any other remedy or relief available to pic3pic.com and/or the Site under equity or law, for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Subscriber Content or if pic3pic.com is concerned that Subscriber may have breached the immediately preceding sentence), or for no reason at all.
                    </p>
                    <h4><b>4. Restrictions</b></h4>
                    <p class="text-justify">
                        Subscriber is responsible for all of its activity in connection with the Services and accessing the Site. Any fraudulent, abusive, or otherwise illegal activity or any use of the Services or Content in violation of this Agreement may be grounds for termination of Subscriber’s right to Services or to access the Site. Subscriber may not post or transmit, or cause to be posted or transmitted, any communication or solicitation designed or intended to obtain password, account, or private information from any pic3pic.com user.
                        Use of the Site or Services to violate the security of any computer network, crack passwords or security encryption codes, transfer or store illegal material including that are deemed threatening or obscene, or engage in any kind of illegal activity is expressly prohibited. Under no circumstances will Subscriber use the Site or the Service to (a) send unsolicited e-mails, bulk mail, spam or other materials to users of the Site or any other individual, (b) harass, threaten, stalk or abuse any person or party, including other users of the Site, (c) create a false identity or to impersonate another person, or (d) post any false, inaccurate or incomplete material or delete or revise any material that was not posted by You.
                    </p>
                    <h4><b>5. Warranty disclaimer</b></h4>
                    <p class="text-justify">
                        pic3pic.com has no special relationship with or fiduciary duty to Subscriber. Subscriber acknowledges that pic3pic.com has no control over, and no duty to take any action regarding: which users gains access to the Site; which Content Subscriber accesses via the Site; what effects the Content may have on Subscriber; how Subscriber may interpret or use the Content; or what actions Subscriber may take as a result of having been exposed to the Content. Much of the Content of the Site is provided by and is the responsibility of the user or subscriber who posted the Content. pic3pic.com does not monitor the Content of the Site and takes no responsibility for such Content. Subscriber releases pic3pic.com from all liability for Subscriber having acquired or not acquired Content through the Site. The Site may contain, or direct Subscriber to sites containing, information that some people may find offensive or inappropriate. pic3pic.com makes no representations concerning any content contained in or accessed through the Site, and pic3pic.com will not be responsible or liable for the accuracy, copyright compliance, legality or decency of material contained in or accessed through the Site.
                        Although pic3pic.com and the Site will make reasonable efforts to store and preserve the material residing on the Site, neitherpic3pic.com nor the Site is responsible or liable in any way for the failure to store, preserve or access Subscriber Content or other materials you transmit or archive on the Site. You are strongly urged to take measures to preserve copies of any data, material, content or information you post or upload on the Site. You are solely responsible for creating back-ups of your Subscriber Content.
                        The Services, Content, Site and any Software are provided on an "as is" basis, without warranties of any kind, either express or implied, including, without limitation, implied warranties of merchantability, fitness for a particular purpose or non-infringement. pic3pic.com makes no representations or warranties of any kind with respect to the Site, the Services, including any representation or warranty that the use of the Site or Services will (a) be timely, uninterrupted or error-free or operate in combination with any other hardware, software, system or data, (b) meet your requirements or expectations, (c) be free from errors or that defects will be corrected, (d) be free of viruses or other harmful components.
                        To the fullest extent allowed by law, pic3pic.com disclaims any liability or responsibility for the accuracy, reliability, availability, completeness, legality or operability of the material or services provided on this Site. By using this Site, you acknowledge that pic3pic.com is not responsible or liable for any harm resulting from (1) use of the Site; (2) downloading information contained on the Site including but not limited to downloads of content posted by subscribers; (3) unauthorized disclosure of images, information or data that results from the upload, download or storage of content posted by subscribers; (4) the temporary or permanent inability to access or retrieve any Subscriber Content from the Site, including, without limitation, harm caused by viruses, worms, trojan horses, or any similar contamination or destructive program.
                        Some places do not allow limitations on how long an implied warranty lasts, so the above limitations may not apply to Subscriber.
                    </p>
                    <h4><b>6. Third party websites</b></h4>
                    <p class="text-justify">
                        Users of the Site may gain access from the Site to third party sites on the Internet through hypertext or other computer links on the Site. Third party sites are not within the supervision or control of pic3pic.com or the Site. Unless explicitly otherwise provided, neither pic3pic.com nor the Site make any representation or warranty whatsoever about any third party site that is linked to the Site, or endorse the products or services offered on such site. pic3pic.com and the Site disclaim: (a) all responsibility and liability for content on third party websites and (b) any representations or warranties as to the security of any information (including, without limitation, credit card and other personal information) You might be requested to give any third party, and You hereby irrevocably waive any claim against the Site or pic3pic.com with respect to such sites and third party content.
                    </p>
                    <h4><b>7. Registration and security</b></h4>
                        As a condition to using Services, Subscriber will be required to register with pic3pic.com and select a password and pic3pic.com URL. Subscriber shall provide pic3pic.com with accurate, complete, and updated registration information, including Subscriber’s e-mail address. Failure to do so shall constitute a breach of this Agreement, which may result in immediate termination of Subscriber's account. Subscriber may not (a) select or use as a pic3pic.com URL a name of another person with the intent to impersonate that person; or (b) use as a pic3pic.com URL a name subject to any rights of a person other than Subscriber without appropriate authorization. pic3pic.com reserves the right to refuse registration of, or cancel a pic3pic.com URL in its discretion. Subscriber shall be responsible for maintaining the confidentiality of Subscriber's pic3pic.com password. Subscriber is solely responsible for any use of or action taken under Subscriber’s password and accepts full responsibility for all activity conducted through Subscriber’s account and agrees to and hereby releases the Site and pic3pic.com from any and all liability concerning such activity. Subscriber agrees to notify pic3pic.com immediately of any actual or suspected loss, theft, or unauthorized use of Subscriber’s account or password. The Site will take reasonably security precautions when using the internet, telephone or other means to transport date or other communications, but expressly disclaims any and all liability for the accessing of any such data communications by unauthorized persons or entities.
                        </p>
                        <h4><b>8. Indemnity</b></h4>
                        <p class="text-justify">
                            Subscriber will indemnify and hold pic3pic.com, its directors, officers and employees, harmless, including costs and attorneys' fees, from any claim or demand made by any third party due to or arising out of Subscriber’s access to the Site, use of the Services, the violation of this Agreement by Subscriber, or the infringement by Subscriber, or any third party using the Subscriber's account, of any intellectual property or other right of any person or entity.
                        </p>
                        <h4><b>9. Limitation of liability</b></h4>
                        <p class="text-justify">
                            In no event shall pic3pic.com, its directors, officers, shareholders, employees or members be liable with respect to the Site or the Services for (a) any indirect, incidental, punitive, or consequential damages of any kind whatsoever; (b) damages for loss of use, profits, data, images, Subscriber Content or other intangibles; (c) damages for unauthorized use, non-performance of the Site, errors or omissions; or (d) damages related to downloading or posting Content. pic3pic.com's and the Site's collective liability under this agreement shall be limited to three hundred Indian Rupess. Some places do not allow the exclusion or limitation of incidental or consequential damages, so the above limitations and exclusions may not apply to Subscriber.
                        </p>
                        <h4><b>11. Termination</b></h4>
                        <p class="text-justify">
                            Either party may terminate the Services at any time by notifying the other party by any means. pic3pic.com may also terminate or suspend any and all Services and access to the Site immediately, without prior notice or liability, if Subscriber breaches any of the terms or conditions of this Agreement,Rules and Regulation and pic3pic Community Guidelines. Upon termination of Subscriber's account, Subscriber’s right to use the Services, access the Site and any Content will immediately cease. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability. Termination of Your access to and use of the Site and the Services shall not relieve Subscriber of any obligations arising or accruing prior to such termination or limit any liability which Subscriber otherwise may have to pic3pic.com or the Site, including without limitation any indemnification obligations contained herein.
                        </p>
                        <h4><b>12. Privacy</b></h4>
                        <p class="text-justify">
                            Please review our Privacy Policy, which governs the use of personal information on the Site and to which Subscriber agrees to be bound as a user of the Site.
                        </p>
                        <h4><b>13. Miscellaneous</b></h4>
                        <p class="text-justify">
                            This Agreement (including the Privacy Policy), as modified from time to time, constitutes the entire agreement between You, the Site and pic3pic.com with respect to the subject matter hereof. This Agreement replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter hereof. The failure of either party to exercise in any respect any right provided for herein shall not be deemed a waiver of any further rights hereunder. pic3pic.com shall not be liable for any failure to perform its obligations hereunder where such failure results from any cause beyond pic3pic.com’s reasonable control, including, without limitation, mechanical, electronic or communications failure or degradation. If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable. This Agreement is not assignable, transferable or sublicensable by Subscriber except with pic3pic.com’s prior written consent. pic3pic.com may assign this Agreement in whole or in part at any time without Subscriber’s consent. This Agreement shall be governed by and construed in accordance with the laws of the state of Delaware without regard to the conflict of laws provisions thereof. No agency, partnership, joint venture, or employment is created as a result of this Agreement and Subscriber does not have any authority of any kind to bind pic3pic.com in any respect whatsoever.
                        </p>
                        <h4><b>14. Notice and Procedure for Making Claims of Copyright or Other Intellectual Property Infringements</b></h4>
                        <p class="text-justify">
                            pic3pic respects the intellectual property of others and takes the protection of copyrights and all other intellectual property very seriously, and we ask our users to do the same. Infringing activity will not be tolerated on or through the Services.
                            pic3pic’s intellectual property policy is to (a) remove material that pic3pic believes in good faith, upon notice from an intellectual property owner or their agent, is infringing the intellectual property of a third party by being made available through the Services, and (b) remove any Subscriber Content posted to the Services by “repeat infringers.” pic3pic considers a “repeat infringer” to be any user that has uploaded Subscriber Content to the Services and for whom pic3pic has received more than two takedown notices compliant with the provisions of The Indian Copyright (Amendment) Act, 2012with respect to such Subscriber Content. pic3pic has discretion, however, to terminate the account of any user after receipt of a single notification of claimed infringement or upon pic3pic’s own determination.
                            Procedure for Reporting Claimed Infringement
                            If you believe that any content made available on or through the Services has been used or exploited in a manner that infringes an intellectual property right you own or control, then please promptly send a “Notification of Claimed Infringement” containing the following information to the Designated Agent identified below. Your communication must include substantially the following:
                            - A physical or electronic signature of a person authorized to act on behalf of the owner of the work(s) that has/have been allegedly infringed;
                            - Identification of works or materials being infringed, or, if multiple works are covered by a single notification, a representative list of such works;
                            - Identification of the specific material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled, and information reasonably sufficient to permit pic3pic to locate the material;
                            - Information reasonably sufficient to permit pic3pic to contact you, such as an address, telephone number, and, if available, an electronic mail address at which you may be contacted;
                            - A statement that you have a good faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and
                            - A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
                            You should consult with your own lawyer.
                            Sent copyright claim Via E-mail:	<b>support@pic3pic.com.</b>
                        </p>
                        <h4><b>Counter Notification</b></h4>
                        <p class="text-justify">
                            If you receive a notification from pic3pic that material made available by you on or through the Services has been the subject of a Notification of Claimed Infringement, then you will have the right to provide pic3pic with what is called a “Counter Notification.” To be effective, a Counter Notification must be in writing, provided to pic3pic’s Designated Agent through one of the methods identified immediately above, and include substantially the following information:
                            - A physical or electronic signature of the subscriber;
                            - Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;
                            - A statement under penalty of perjury that the subscriber has a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material to be removed or disabled; and
                            - The subscriber’s name, address, and telephone number, and a statement that the subscriber consents to the jurisdiction of Federal District Court for the judicial district in which the address is located, or if the subscriber’s address is outside of the United States, for any judicial district in which pic3pic may be found, and that the subscriber will accept service of process from the person who provided a Notification of Claimed Infringement as set forth above or an agent of such person.
                            A party submitting a Counter Notification should consult a lawyer or see The Indian Copyright (Amendment) Act, 2012to confirm the party’s obligations to provide a valid counter notification under the Copyright Act.
                            pic3pic Actions Following Receipt of Counter Notification
                            Upon receipt of a Counter Notification, pic3pic shall promptly provide the party submitting a Notification of Claimed Infringement with a copy of the Counter Notification, and pic3pic will replace the removed material or cease disabling access to it in not less than 10, nor more than fourteen (14), business days following receipt of the Counter Notice, unless pic3pic’s Designated Agent first receives notice from the person who submitted the Notification of Claimed Infringement that such person has filed an action seeking a court order to restrain the subscriber from engaging in infringing activity relating to the material on pic3pic’s system or network.
                            False Notifications of Claimed Infringement or Counter Notifications
                        </p>
                        <h4><b>The Copyright Act provides that:</b></h4>
                        <p class="text-justify">
                            Any person who knowingly materially misrepresents under (1) that material or activity is infringing, or (2) that material or activity was removed or disabled by mistake or misidentification, shall be liable for any damages, including costs and attorneys’ fees, incurred by the alleged infringer, by any copyright owner or copyright owner’s authorized licensee, or by a service provider, who is injured by such misrepresentation, as the result of [pic3pic] relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing, or in replacing the removed material or ceasing to disable access to it.
                            pic3pic reserves the right to seek damages from any party that submits a Notification of Claimed Infringement or Counter Notification in violation of the law.
                            For the avoidance of doubt, only notices submitted under The Indian Copyright (Amendment) Act, 2012and the procedures set forth in this Agreement should be sent to the Designated Agent at copyright@pic3pic.com or to the postal address identified above. Any other comments, compliments, complaints or suggestions about pic3pic, the operation of the Services or any other matter should be sent to <b>support@pic3pic.com.</b>
                        </p>       
                </div>
            </div>
                 